export const PRODUCTS = [
    {
        id: 0,
        name: "Milk Tea",
        image: "../images/MilkTea.jpg",
        price: 20000,
        category: "tea",
        options: "Iced",
        featured: false,
    },
    {
        id: 1,
        name: "Matcha Green Tea",
        image: "../images/MatchaGreenTea.webp",
        price: 20000,
        category: "tea",
        options: "Iced",
        featured: true,
    },
    {
        id: 3,
        name: "Peach Tea",
        image: "../images/PeachTea.jpg",
        price: 15000,
        category: "tea",
        options: "Iced",
        featured: false,
    },
    {
        id: 4,
        name: "Black Coffee",
        image: "../images/BlackCoffee.jpg",
        price: 15000,
        category: "coffee",
        options: "Hot, Iced",
        featured: false,
    },
    {
        id: 5,
        name: "White Coffee",
        image: "../images/WhiteCoffee.jpg",
        price: 15000,
        category: "coffee",
        options: "Hot, Iced",
        featured: false,
    },
    {
        id: 6,
        name: "Tiramisu",
        image: "../images/Tiramisu.jpg",
        price: 22000,
        category: "pastry",
        featured: true,
    },
    {
        id: 7,
        name: "Cheese Cake",
        image: "../images/CheeseCake.jpg",
        price: 23000,
        category: "pastry",
        featured: false,
    },
    {
        id: 8,
        name: "Latte",
        image: "../images/Latte.jpg",
        price: 25000,
        category: "coffee",
        options: "Hot, Iced",
        featured: true,
    },
    {
        id: 9,
        name: "Pudding",
        image: "../images/Pudding.jpg",
        price: 20000,
        category: "pastry",
        featured: false,
    },
    
];